`define REG_A_LOAD              'd0
`define REG_B_LOAD              'd1
`define ALU_OPC_0               'd2
`define ALU_OPC_1               'd3
`define ALU_OPC_2               'd4
`define ALU_OPC_3               'd5
`define ALU_OPC_4               'd6
`define REG_F_LOAD              'd7
`define REG_F_OUT               'd8
`define ALU_OUT                 'd9
`define REG_TMPH_LOAD           'd10
`define REG_TMPL_LOAD           'd11
`define REG_TMPH_OUT            'd12
`define REG_TMPL_OUT            'd13
`define REG_TMP_PASS_ADDRESS    'd14
`define REG_TMPH_PASS_DATA      'd15
`define REG_TMPL_PASS_DATA      'd16
`define REG_TMP_ADDRESS_DIR     'd17
`define REG_TMPH_DATA_DIR       'd18
`define REG_TMPL_DATA_DIR       'd19
`define PC_LOAD                 'd20
`define PC_RST                  'd21
`define PC_TICK                 'd22
`define PC_OUT                  'd23
`define STC_LOAD                'd24
`define STC_RST                 'd25
`define STC_TICK                'd26
`define STC_MODE                'd27
`define STC_OUT                 'd28
`define REG_MAR_LOAD            'd29
`define REG_MBR_LOAD            'd30
`define MEM_OUT                 'd31
`define MEM_IN                  'd32
`define MEM_PART                'd33
`define ZERO_PAGE               'd34
`define REG_MBR_WORD_DIR        'd35
`define REG_MAR_USE_BTTNS       'd36
`define REG_MBR_USE_BTTNS       'd37
`define REG_MBR_USE_BUS         'd38
`define REG_IR_LOAD             'd39
`define MCC_TICK                'd40 
`define MCC_RST                 'd41
